require 'kappa/id_equality'
require 'kappa/proxy'
require 'kappa/status'
require 'kappa/errors'
require 'kappa/connection'
require 'kappa/configuration'
require 'kappa/query'
require 'kappa/channel'
require 'kappa/stream'
require 'kappa/game'
require 'kappa/video'
require 'kappa/team'
require 'kappa/user'
require 'kappa/images'
require 'kappa/version'

# V5 resources
require 'kappa/v5/query'
require 'kappa/v5/channel'
require 'kappa/v5/stream'
require 'kappa/v5/game'
require 'kappa/v5/video'
require 'kappa/v5/team'
require 'kappa/v5/user'
require 'kappa/v5/images'
